name: Node.js CI/CD

on:
  push:
    branches: [main, dev]

env:
  DEFAULT_NODE_VERSION: "20.x"
  NODE_VERSION: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: pwd

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: check Node.js version
        run: cat .nvmrc >> $NODE_VERSION

      - name: print NODE_VERSION
        run: cat "NODE_VERSION

      - if: ${{env.NODE_VERSION == ''}}
        run: echo "${{env.DEFAULT_NODE_VERSION}}" >> ${{env.NODE_VERSION}}

      - run: echo "${{env.NODE_VERSION}}"

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "pnpm"

      - name: pnpm ci
        run: pnpm install --frozen-lockfile
      - name: pnpm test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: pnpm ci
        run: pnpm install --frozen-lockfile
      - name: pnpm build
        run: pnpm build
