name: Node.js CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: pwd

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install pnpm
        run: npm install -g pnpm
      - name: pnpm ci
        run: pnpm install --frozen-lockfile
      - name: pnpm test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install pnpm
        run: npm install -g pnpm
      - name: pnpm ci
        run: pnpm install --frozen-lockfile
      - name: pnpm build
        run: pnpm build
